# # config/validator/validation.yaml
# App\Vk\HealthCareBundle\Entity\UserPost:
#     properties:
#         image:
#             - File:
#                 maxSize: 1024k
#                 mimeTypes: [image/jpeg, image/jpg, image/png]
#                 mimeTypesMessage: Please upload a valid jpeg,jpg,png
